## The Tensorflow Trials

<a target="_blank" href="https://colab.research.google.com/github/toelt-llc/HSLU-NLP-Bootcamp/blob/main/Day_2/Transformers_Hands-On/Tensors_Intro/tensorflow-trials.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

Over the course of today's challenges, you'll be manipulating tensors extensively and working with some unconventional model architectures. 

In this warm up, you'll be introduced to some new methods. 

All the methods here are going to make tackling challenges later in the day 100x easier, so if you do get stuck later on, make sure you come back here to see how you achieved the right answers. 

In [1]:
import tensorflow as tf

2025-03-18 18:29:45.839087: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


A) Use `tf.ones` to create a tensor `a` filled with ones of shape (3,3).

In [2]:

a = tf.ones(shape = (3,3))


B) Use tf.expand_dims to make `a` an object of shape (1,3,3) called `b`.

In [3]:

b = tf.expand_dims(a, 0)
print(b.shape)


(1, 3, 3)


C) Create a tensor `c` filled with zeroes of size (9,1)

In [4]:

c = tf.zeros(shape = (9,1))


D) Reshape `c` to be of shape (1, 3, 3). Name it `d`.

In [5]:

d = tf.reshape(c, shape = (1,3,3))


E) Use `tf.matmul` to matrix multiply `b` and `d` with each other and now assign the tensor to `e`. 

In [6]:

e = tf.matmul(b, d)


F) Below is a `numpy` array. Convert it to a tensor named `array_tensor`. Then use `tf.cast` to ensure it is of dtype `float` not `int`. Assign the result to `f`.

In [7]:
import numpy as np

In [8]:
array = np.array([[
    [1,2,3],
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])

In [9]:

array_tensor = tf.convert_to_tensor(array)
f = tf.cast(array_tensor, float)


G) Select the values in the __last column__ of `f` and save this to `g`. To be clear, `g` should have shape (4,) and contain the values `3,3,6,9`. 

In [10]:

g = f[0,:,-1]


H) Expand the dimensions of g so that it's of shape (4,1). Assign this to `h`.

In [11]:

h = tf.expand_dims(g, -1)
print(h.shape)


(4, 1)


I) Multiply e with f, using `tf.matmul` with the optional `transpose_b` argument (`e` must come first in your positional arguments, then `f`). Assign this to `i`.

In [12]:

i = tf.matmul(e, f, transpose_b=True)


J) Create a `(10,10)` tensor filled with ones. Then use `tf.linalg.band_part()` to mask out the upper triangle of the matrix (i.e. the upper triangle should all be 0s). Assign to `j`.

In [13]:

ones = tf.ones((10,10))
j = tf.linalg.band_part(ones, -1, 0)


K) Take the `number_list` below and make it a tensor. Assign it to `k`.

In [14]:
number_list = [1,2,3,4,8]

In [15]:

k = tf.convert_to_tensor(number_list)


L) Use `tf.expand_dims` to make `k` into a tensor of shape (1,5). Assign to `l`.

In [16]:

l = tf.expand_dims(k, 0)


M) Use `tf.tile` to repeat `l` (read as "L") 50 times, with an eventual shape of `(50, 5)`. Assign to `m`.

In [17]:

m = tf.tile(l, (50,1))


N) Use a simple Boolean statement to create a tensor containing `True` values for where `m` is 3  and `False` for where it is not 3. Assign to `n`

In [18]:

n = m == 3


O) Divide every value in you variable `m` by 3. Assign to `o`.

In [19]:

o = m/3


P) Use `tf.concat()` to take the list of two tensors below of shape (5,5) and (5,5) each and turn them into a final tensor of shape (10,5). Assign to `p`. Think carefully about the concation axis.

In [20]:
tensor_list = [tf.ones((5,5)), tf.ones((5,5))]

In [21]:

p = tf.concat(tensor_list, axis=0)


### Check your answers

In [22]:
results_dict = {
    "a": a,
    "b": b,
    "c": c,
    "d_shape": d.shape ,
    "e": e,
    "f": f,
    "g": g,
    "i": i,
    "j": j,
    "k": k,
    "l": l,
    "m": m,
    "n": n,
    "o": o,
    "p_shape": p.shape,
}

display(results_dict)

{'a': <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 'b': <tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 'c': <tf.Tensor: shape=(9, 1), dtype=float32, numpy=
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=float32)>,
 'd_shape': TensorShape([1, 3, 3]),
 'e': <tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
 array([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=float32)>,
 'f': <tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
 array([[[1., 2., 3.],
         [1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]], dtype=float32)>,
 'g': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([3., 3., 6., 9.], dtype=float32)>,
 'i': <tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
 array([[[0., 0., 0.,

In [23]:
import pytest

# Inject results dictionary into test module before running pytest
import test_tensors
test_tensors.results_dict = results_dict

pytest.main(["test_tensors.py"])


============================= test session starts ==============================
platform darwin -- Python 3.12.0, pytest-8.3.5, pluggy-1.5.0
rootdir: /Users/arnaud/Documents/GitHub/bootcamp_fs2025/Transformers_Hands-On/Tensors_Intro
plugins: anyio-4.8.0, typeguard-4.3.0
collected 15 items

test_tensors.py ...............                                          [100%]

============================== 15 passed in 0.22s ==============================


<ExitCode.OK: 0>

### Great work !